var_names_int: ["pr", "rlut", "rsut", "rsutcs", "rlutcs", "lwp", "clvi", "clivi", "dsevi"]
var_names_prof: ["ta", "hus", "clw", "cli", "tke", "wa", "hur", "cl", "arup", "entr"]
z_levels: [100, 300, 500, 700, 850, 1000, 1150, 1300, 1500, 2000, 2500, 3000, 4000]
reduction_start_time: 64800
reduction_end_time: 108000
exp_name: "expanded_levels"
prior_path: "prior.toml"
